### ISSUE TITLE
[01-05 ~ 01-11] Todo List

### ISSUE THREAD

**Issue by jun108059** [jun108059/til#2]
### **`Docker + Kubernetes 환경 구축`**

- [x] Docker 공부+구현
- [x] Kubernetes 공부+구현
- [x] 자료구조&알고리즘 강의 매일매일

**Comment by jun108059** [comment]
## 피드백
+ Kubernetes 구현 못함
+ 알고리즘 강의 이틀에 하나씩 듣기로 변경

## 추가된 내용
+ Flutter Study + 프로젝트
+ Machine Learning Study
+ 블로그 이전
