### ISSUE TITLE
[01-12 ~ 01-18] Todo List

### ISSUE THREAD

**Issue by jun108059** [jun108059/til#3]
### **`OPIC 학원, Flutter 공부, ML 공부 `**

- [x] Flutter Udemy 강의 (~section 11)
- [x] OPIC 학원 + 스터디
- [x] 자료구조&알고리즘 강의 3개
- [x] Machine Learning Chapter 2까지 정리

**Comment by jun108059** [comment]
## 추가된 내용
+ OPIC 학원 추가 스터디
