### ISSUE TITLE
[01-19 ~ 01-25] Todo List

### ISSUE THREAD

**Issue by jun108059** [jun108059/til#4]
### **`OPIC 학원, Flutter 공부, ML 공부 `**

- [x] Flutter Udemy 강의
- [x] OPIC 학원 + 스터디
- [x] 자료구조&알고리즘 강의 3개
- [x] Machine Learning Chapter 3까지 정리
