### ISSUE TITLE
[01-26 ~ 02-01] Todo List 

### ISSUE THREAD

**Issue by jun108059** [jun108059/til#5]
### **`OPIC 학원, Flutter 공부, ML 공부 `**

- [x] **OPIC 시험 준비** (2월1일)
- [x] Flutter Udemy 강의
- [x] Flutter 프로젝트
- [x] OPIC 학원 + 스터디
- [x] 자료구조&알고리즘 강의 3개
- [x] Machine Learning Chapter 4까지 정리
