### ISSUE TITLE
[02-02 ~ 02-08] Todo List 

### ISSUE THREAD

**Issue by jun108059** [jun108059/til#6]
### **`Flutter 프로젝트, ML  환경설정 `**

- [x] ML(Linux) PC 환경설정
- [x] Flutter Udemy 강의
- [x] Flutter 프로젝트
- [x] 자료구조&알고리즘 강의 3개
- [x] Machine Learning Chapter 5까지 정리
